### ISSUE TITLE
Some issues installing the new installation

### ISSUE THREAD

**Issue by nadabrovitxka** [hms-dbmi/higlass-manage#4]
Sorry for bundling issues.
Have a new machine and just started installing Higlass from scratch following [this:](https://docs.higlass.io/atutorial.html#running-higlass-locally)
after installing doing:

`higlass-manage start`

Gave me an error relating to bed files ingestion.

> print('An assembly or set of chromosome sizes is required when importing bed files. Please specify one or the other using the --assembly or --chromsizes-filename parameters', file=sys.stderr)

I think this is pointing to something wrong.
What I realized was causing the issue was that I had python 2 instead of 3.
Once I updated, `higlass-manage start`, created the hg-data folder and starts
This
`higlass-manage browse `
leads to

> Error: No such command "browse".

Higlass still opens on http://localhost:8989 but not on http://localhost:8989/app as you describe.

Hope this helps.

**Comment by pkerpedjiev** [comment]
Thanks for pointing this out! Should be fixed in v0.1.14, which will be pushed to pypi in a day or two.
