### ISSUE TITLE
Error, No such image: gehlenborglab/higlass:latest

### ISSUE THREAD

**Issue by ssmadha** [hms-dbmi/higlass-manage#7]
I am trying to start higlass-manage I use says that it is `Pulling latest image...`, however ends up erroring out with the message `docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: gehlenborglab/higlass:latest: No such image: gehlenborglab/higlass:latest")`. I've tried v0.2.1, 0.2.0 and 0.1.13, and all have the same message.

**Comment by pkerpedjiev** [comment]
Strange. I just tried it and worked fine. 

Are you sure your Docker client is running? Could you try the following commands?

```
docker stop higlass-container; 
docker rm higlass-container;

docker pull gehlenborglab/higlass;
```

**Comment by ssmadha** [comment]
Ah, that helped me realize the drive where my docker stuff was put didn't have enough space. In case anyone else comes across the same issue, [this](https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169) gives instructions on how to change where docker stores stuff.

**Comment by pkerpedjiev** [comment]
Thank you for following up with your solution!
